name: CI
on:
  push:
    branches: [ develop, test/* ]
  pull_request:
    branches: [ develop ]
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: true
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          buildWithCMakeArgs: "--parallel"
  build-ios:
    name: Build (ios-latest)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - run: |
          cmake -B crashpad-xcode -GXcode -DCMAKE_SYSTEM_NAME=iOS
          xcodebuild build -project crashpad-xcode/crashpad.xcodeproj
  success:
    name: Success
    if: ${{ success() }}
    needs: [ build, build-ios ]
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: exit 0
